#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IF=$(iw dev | awk '$1=="Interface"{print $2}')


CONF_FILE="config.cfg"
LOG_ASAU="$DIR/wireless/tu/log/tmp_log"
WPA_CONF="$DIR/wireless/configuration/files/wpa.conf"


while getopts "c:vh" option; do
    case "${option}" in
        c)
            CONF_FILE="${OPTARG}"
            C=1
            ;;
        h)
            cat <<- EOF
Usage: ./autorun [OPTIONS]

Options:
    -h
        Affiche ce message d'aide et quitte.

    -c <fichier>
        Spécifie le fichier de configuration à utiliser.
        Exemple : ./autorun -c /path/to/config.cfg

EOF
    exit 0
    ;;
    esac
done


if [[ "$C" -eq 0 ]]; then #s'il n'y a pas de fichier de configuration de spécifié, on les fixe manuellement
    IF=$IF
    TEST_INTERVAL=10
    THRESHOLD_SIGNAL=-70
    TXPOWER=15dBm
    DNS=1
    DNS_TARGET="univ-lyon1.fr"
    HTTP=1
    HTTP_TARGET="https://www.univ-lyon1.fr"
    PING=1
    PING_NUMBER=4
    PING_TARGET="1.1.1.1"
fi


if [[ "$C" -eq 1 ]]; then # on lit les paramètres du fichier de configuration spécifié
    source $CONF_FILE
fi

# Le but de ce script est d'automatiser le lancement des tests unitaires 
# les uns à la suite des autres et de vérifier que tout se passe comme prévu.

# Etape 1 : scanner les bssid aux alentours avec un signal supérieur au signal spécifié 
#           et récuperer le nombre de bssid disponibles



while true; do
    
    #echo -e "----------------------------   Remise à zéro des configurations    ----------------------------\n"
    $DIR/wireless/reset/reset_config -i $IF #Fin de l'assoc/auth

    
    TOTAL_BSSID=$($DIR/wireless/configuration/script/get_bssids -s "$SSID_TARGET" -t $THRESHOLD_SIGNAL -i $IF -n)
    
    echo "TOTAL BSSID: " $TOTAL_BSSID
    
    
    # Etape 2 : Boucler sur les ssid
        # Créer la configuration d'association/authentification pour le ieme bssid
        # Test d'assoc/auth
        # Test Demande DHCP
        # Test ICMP
        # Test DNS 
        # Test Curl ???
    
    INTERVAL_MS=$((TEST_INTERVAL * 60))
    for (( i=1; i<$TOTAL_BSSID + 1; i++ ))
        do
    
            #"----------------------------   Creation de la configuration        ----------------------------\n"
            $DIR/wireless/configuration/script/create_conf -n $i -s "$SSID_TARGET" # Creation de la configuration pour l'association/authentification
    
            #"----------------------------   Association et authentification     ----------------------------\n"
    
            # on récupère le bssid actuel depuis le fichier de configuration
            CB=$(cat "$WPA_CONF" | grep "bssid" | awk -F '=' '{print $2}')
    
            # on lance la commande d'assoc/auth et on garde la sortie de la commande afin de calculer le temps d'assoc/auth
            # on garde aussi le pid pour tuer le proc à la fin des tests
            # on laisse le temps à l'assoc/auth de se faire
            wpa_supplicant -t -i $IF -c $WPA_CONF > $LOG_ASAU 2>&1 &
    
            timeout 50s tail -n +1 -f "$LOG_ASAU" 2>/dev/null | grep -q -m 1 "CTRL-EVENT-CONNECTED" 
            # le timeout permet de lancer une commande avec un temps d'attente maximal (ici, 50 secondes) et 
            # de se stopper lorsque la commande s'est terminé ou au bout du temps maximal si la commande n'a pas abouti
    
            # on récupère le timestamp en débit de fichier ainsi que celui de confirmation d'auth
    
            if [ $? -eq 0 ]; then
                startAA=$(head -n 1 "$LOG_ASAU" | awk -F ':' '{print $1}')
                endAA=$(grep -m 1 "CTRL-EVENT-CONNECTED" "$LOG_ASAU" | awk -F ':' '{print $1}')
    
                if [ -z "$endAA" ]; then endAA=$startAA; fi
    
                AT=$(echo "$endAA $startAA" | awk '{printf "%.3f", $1 - $2}')
    
                if (( $(awk "BEGIN {print ($AT < 4)}") )); then
                    STATUS=0
                elif (( $(awk "BEGIN {print ($AT < 8 && $AT > 4)}") )); then
                    STATUS=1
                elif (( $(awk "BEGIN {print ($AT < 15 && $AT > 8 )}") )); then
                    STATUS=2
                elif (( $(awk "BEGIN {print ($AT > 15 )}") )); then
                    STATUS=3
                fi
            else
                STATUS=4
            fi
    
            # une fois, le temps calculé, on fixe le statut de l'association selon la durée pour l'envoyer au serveur syslog et fixer le bon niveau de sévérité correspondant
            # si le statut est 4, alors l'assoc/auth ne s'est pas effectué
    
    
            echo "{\"service\" : \"ASAU\" , \"status\" : $STATUS , \"bssid\" : \"$CB\" , \"duration\": $AT}"
    
            if [[ $STATUS -eq 0 || $STATUS -eq 1  || $STATUS -eq 2 || $STATUS -eq 3 ]]; then
    
                #"----------------------------   Demande de configuration DHCP       ----------------------------\n"
    
                startDHCP=$(date +"%s.%3N")
    
                dhclient $IF > /dev/null 2>&1 # on demande la configuration réseau via dhclient
    
                STAT=$?
    
                endDHCP=$(date +"%s.%3N")
    
                DHCPT=$(echo "$endDHCP $startDHCP" | awk '{printf "%.3f", $1 - $2}')
    
                echo "{\"service\" : \"DHCP\" , \"status\" : $STAT , \"bssid\" : \"$CB\" , \"duration\" : $DHCPT}"

                timeout -s SIGTERM 10s $DIR/wireless/monitoring/get_infos -i 0.5 -I $IF -b $CB
    
                if [[ $STAT -eq 0 ]]; then
    
                    #"----------------------------   Vérification de configuration IP    ----------------------------\n"
    
                    IPAMSR=$(ip -4 addr show $IF | grep -E "inet ([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2} brd ([0-9]{1,3}\.){3}[0-9]{1,3}" | xargs | awk -F ' ' '{print $2}')
    
                    IPA=$(echo $IPAMSR | cut -d '/' -f1)
                    MSR=$(echo $IPAMSR | cut -d '/' -f2)
    
                    IPR=$(ip route show default dev $IF | awk -F ' ' '{print $3}')
    
                    STATUS=$? # on tente de lire l'adresse IP et l'adresse de la passerelle pour l'interface choisie
    
                    echo -e "{\"service\" : \"IPConfig\" , \"status\" : $STATUS ,  \"bssid\" : \"$CB\" , \"address\" : \"$IPA\" , \"subnet_mask\" : \"$MSR\" ,\"gateway\": \"$IPR\"}"
    
    
                    if [[ $DNS -eq 1 ]]; then
                        # "----------------------------   Résolution DNS                      ----------------------------\n"
    
                        $DIR/appli/dns_check -v -d $DNS_TARGET -i $IPA -b $CB # on appelle le script de résolution DNS avec les bons paramètres
    
                    fi
    
    
                    if [[ $PING -eq 1 ]]; then
                        # "----------------------------   Test de connectivité                ----------------------------\n"
    
                        $DIR/appli/icmp_check -c $PING_NUMBER -t $PING_TARGET -i $IF -b $CB # on appelle le script de résolution ICMP avec les bons paramètres
                    fi
    
                    if [[ $HTTP -eq 1 ]]; then
                        # "----------------------------   Test de connectivité WEB                ----------------------------\n"
    
                        $DIR/appli/http_check -u $HTTP_TARGET -i $IF -b $CB # on appelle le script de résolution HTTP avec les bons paramètres
    
                    fi
                fi
    
            fi    
        done

    sleep $INTERVAL_MS
done
