#!/bin/bash

IF=$(iw dev | awk '$1=="Interface"{print $2}')
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while getopts "hi:" option; do
    case "${option}" in
        i)
            IF="${OPTARG}"
            ;;
        h)
            cat <<- EOF
Usage: ./get_status [OPTIONS]

Options:
    -h
        Affiche ce message d'aide et quitte.

    -i <Interface sans fil>
        Permet de spécifier l'interface sans fil.
EOF
    exit 0
    ;;
    esac
done

iw dev $IF link > $DIR/status

if cat $DIR/status | grep -q "Not connected"; then
    STATUS="Not connected"
    echo -e "{\"service\" : \"WirelessStatus\" , \"status\" : \"$STATUS\"}"
else
    STATUS="Associated and authenticated"
    BSSID=$(cat $DIR/status | grep "Connected" | cut -d' ' -f3)
    SSID=$(cat $DIR/status | grep "SSID" | cut -d' ' -f2)
    SIGNAL=$(cat $DIR/status | grep "signal" | cut -d' ' -f2,3)
    FREQ=$(cat $DIR/status | grep "freq" | cut -d ' ' -f2 | cut -d'.' -f1)
    
    IPAMSR=$(ip -4 addr show $IF | grep -E "inet ([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2} brd ([0-9]{1,3}\.){3}[0-9]{1,3}" | xargs | awk -F ' ' '{print $2}')

    IPA=$(echo $IPAMSR | cut -d '/' -f1)
    MSR=$(echo $IPAMSR | cut -d '/' -f2)

    IPR=$(ip route | grep $IF | grep default | awk -F ' ' '{print $3}' | uniq)
    
    echo -e "{\"service\" : \"WirelessStatus\", \"status\" : \"$STATUS\", \"BSSID\" : \"$BSSID\", \"SSID\" : \"$SSID\", \"SIGNAL\" : \"$SIGNAL\", \"FREQ\" : \"$FREQ\",
    \"IPA\" : \"$IPA"/"$MSR\", \"IPR\" : \"$IPR\" }"
fi
