#!/bin/bash

IF=$(iw dev | awk '$1=="Interface"{print $2}')

while getopts "i:h" option; do
    case "${option}" in
        i)
            IF="${OPTARG}"
            ;;
        h)
            cat <<- EOF
Usage: ./ip_check_config [OPTIONS]

Options:
    -h
        Display this help message and exit.

    -i <Wireless interface>
        Allows specifying the wireless interface.

    -b <BSSID>
        Specify the BSSID.
EOF
    exit 0
    ;;
    esac
done


IPAMSR=$(ip -4 addr show $IF | grep -E "inet ([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2} brd ([0-9]{1,3}\.){3}[0-9]{1,3}" | xargs | awk -F ' ' '{print $2}')

IPA=$(echo $IPAMSR | cut -d '/' -f1)
MSR=$(echo $IPAMSR | cut -d '/' -f2)

IPR=$(ip route | grep $IF | grep default | awk -F ' ' '{print $3}' | uniq)

STATUS=$?

echo -e "{\"service\" : \"IPConfig\" , \"status\" : $STATUS , \"bssid\" : \"$B\" , \"address\" : \"$IPA\" , \"subnet_mask\" : \"$MSR\" ,\"gateway\": \"$IPR\"}"



