- name: Try to associate and to authenticate with wpa_supplicant
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Script execution
      command: /opt/client/wireless/tu/association_check -i {{ interface }}
      register: script_output
      changed_when: false

    - name: Return script output
      debug:
        msg: "{{ script_output.stdout }}"