- name: Request for every wireless interface on a probe
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
    - name: Script execution
      command: /opt/client/wireless/configuration/script/get_interfaces
      register: script_output
      changed_when: false

    - name: Return script output
      debug:
        msg: "{{ script_output.stdout }}"