
- name: Wireless Monitoring
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
    - name: Script execution
      command: /opt/client/wireless/monitoring/get_infos -i {{ intervalle }} -I {{ interface }}
      register: script_output
      changed_when: false

    - name: Return script output
      debug:
        msg: "{{ script_output.stdout }}"