
- name: Wireless Status
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
    - name: Script execution
      command: /opt/client/wireless/monitoring/get_status -i {{ interface }} -b {{ bssid }}
      register: script_output
      changed_when: false

    - name: Return script output
      debug:
        msg: "{{ script_output.stdout }}"